### ISSUE TITLE
Pulling repository docker.io/library/repenv

### ISSUE THREAD

**Issue by santteegt** [dougmet/repEnvDemo#3]
Hi,

please, let us know when you fix the problem that came out during the presentation.

Thanks.

**Comment by dougmet** [comment]
Hi,

Yes really annoyed with myself about that. In the heat of the moment I forgot that all I had to do was run (from project root):

```
docker build machine -t repenv
```

And this builds the machine. If you don't already have dougmet/r-base:3.1.2 (which I did) it will pull that image and then install the small number of R dependencies. In my case (because I've done it before) it was very fast. When it's your first time it will take a minute or two.

When that's done you can either run:

```
shell/runScript.sh
```

or

```
docker run --rm -v $PWD:/home/docker/host repenv Rscript /home/docker/host/script.R
```

if you're on Windows $PWD probably won't work. You could try replacing it with the full path

```
//c/Users/<USERNAME>/path/to/project
```

When it runs the output should look like:

```

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

null device 
          1 
null device 
          1 
```

And you'll find the pdfs in the `results` directory.

Let me know if that works for you.

**Comment by dougmet** [comment]
It also turned out that I had previously built the image and given it a different name. Oh well, such is the nature of the live demo.

**Comment by santteegt** [comment]
yes, now it works.

Thanks
